---
ops: [analyze]
model: {
    path: <PATH>/model/sei.py,
    class: Sei,
    class_args: {
    },
    non_strand_specific: mean
}
analyze_sequences: !obj:selene_sdk.predict.AnalyzeSequences {
    sequence_length: 4096,
    batch_size: 128,
    trained_model_path: <PATH>/model/sei.pth,
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: <PATH>/model/target.names
    },
    write_mem_limit: 1000
}
prediction:  {
    output_format: hdf5
}
random_seed: 999
...
